### ISSUE TITLE
Player spawning in unloaded world creates new world

### ISSUE THREAD

**Issue by Tzky** [trentech/ProjectWorlds#1]
What went wrong
---
If a player played on a world which got removed while he was disconnected, the plugin will currently create a new world called ``Overworld`` and spawn the player there. 

Additionally it's not possible to ``/unload`` or ``/delete`` ``Overworld``, when you reload the previously unloaded world and ``/tp`` there.

What i expected to happen
---
The player should spawn in either: 
* a special respawn world specified in the plugins config
* on the ``respawnworld`` specified for the unloaded world

How to reproduce:
---

1. load an additional world (here: ``MineCon``)
2. ``/tp`` yourself to ``MineCon``
3. disconnect
4. someone else does ``/w unload MineCon`` while you're disconnected
5. reconnect
6. ``Overworld`` gets created, you spawn there instead of ``MineCon``, same coords as when you left

Now we try to remove ``Overworld``:

7. now ``/w load MineCon``
8. ``/tp`` to MineCon
9. Now ``Overworld`` can't be unloaded or deleted even if ``/w list`` reports that it *is* unloaded
10. leave ``MineCon`` again (tp to *any* other world than MineCon or Overworld)
11. ``Overworld`` can get unloaded and deleted again via ``/w unload`` and ``/w delete``

**Comment by trentech** [comment]
I believe this is partly a implementation issue. I will be opening a ticket on the Sponge github page

**Comment by trentech** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/e76599f7266a22ca9a553dccb4ff34c1c4c59558

Fixes this
