### ISSUE TITLE
"You do not have permission to use this command!"

### ISSUE THREAD

**Issue by Keaft** [trentech/ProjectWorlds#10]
Trying to teleport as a member of the "Guest" group.

/world teleport museum - or - /pjw world teleport museum
and
/world teleport world - or - /pjw world teleport world

http://pastebin.com/cBsFCJrd

Oh the joys of establishing a new permissions system in any context among any of the technical fields.
I've got a good feeling the problem is between the seat and the steering wheel. Lemme know what I'm missing.

**Comment by trentech** [comment]
Was this edited by hand?

**Comment by Keaft** [comment]
My mere mortal mittens did indeed edit it. I just went back through and tried all through the console/in-game. I'll test a few more things before I come back with more of the juicy details.

**Comment by trentech** [comment]
Closing as a Pex configuration issue, not PJW
