### ISSUE TITLE
Cant get worlds to generate with...well...anything

### ISSUE THREAD

**Issue by Vionai** [trentech/ProjectWorlds#102]
Every time I generate a world, it ignores the seed I give it. It also makes it generate with zero structures: No water temples, no villages, nothing. Regardless o the perimeters I assign it.

I'm very frustrated. All i wanted was a regular survival minecraft world to go along with our hub.

**Comment by trentech** [comment]
confirmed however appears to be a bug in Sponge. I was able to reproduce the issue but also confirm that the created test worlds are set with the correct seed and parameters, however still producing unexpected results. Will be reporting the Sponge team

**Comment by trentech** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/2240

**Comment by trentech** [comment]
This issue has been resolved with latest Sponge release
