### ISSUE TITLE
On startup - java.lang.NullPointerException at net.minecraft.world.storage.WorldInfo.isEnabled(WorldInfo.java:514) ~[ato.class:?]

### ISSUE THREAD

**Issue by ProsperCraft** [trentech/ProjectWorlds#11]
http://pastebin.com/ZE7gkSM7

projectworlds-4.1.0-0.8.56.jar

**Comment by GershonR** [comment]
Same error:
http://pastebin.com/9uizKieW

**Comment by trentech** [comment]
What version of Sponge are you running? This is an old error in Sponge that was resolved a while ago

**Comment by GershonR** [comment]
1.8.9 - 4.1.0-BETA-1212 the latest one

**Comment by ProsperCraft** [comment]
Same 1212

**Comment by trentech** [comment]
Does this error also appear when using the "/world enable" command? 

I will have to ping one of the Sponge devs. This is an Sponge implementation error.

**Comment by GershonR** [comment]
This error appears on startup each time.

**Comment by trentech** [comment]
I got that but I want to know if it also appears running /world enable as well.

**Comment by trentech** [comment]
Clicked wrong button

**Comment by GershonR** [comment]
> 21.03 00:00:44 [Server] Server thread/INFO [io.github.hsyyid.essentialcmds]: [Server] executed command pjw:world enable DIM1 true
> 21.03 00:00:44 [Server] Server thread/INFO Set enabled of DIM1 to true
> 21.03 00:01:00 [Server] Server thread/INFO [io.github.hsyyid.essentialcmds]: [Server] executed command pjw:world enable DIM-1 true
> 21.03 00:01:00 [Server] Server thread/INFO Set enabled of DIM-1 to true
> 21.03 00:01:15 [Server] Server thread/INFO [io.github.hsyyid.essentialcmds]: [Server] executed command pjw:world enable DIM-1 false
> 21.03 00:01:15 [Server] Server thread/INFO Set enabled of DIM-1 to false

It does not.

**Comment by trentech** [comment]
Interesting. OK I'll have to discuss this with the Sponge guys but in the mean time I'll push a update tomorrow that'll stop the error.

**Comment by trentech** [comment]
3119ce87744201071ef2c0483047d9caebdda74e
