### ISSUE TITLE
Can't use /world create

### ISSUE THREAD

**Issue by Huckletsplay** [trentech/ProjectWorlds#15]
https://gyazo.com/c873eb89e56ff43d79dfe5c01f3acc11  this is what it tells me

**Comment by trentech** [comment]
Some of those commands listed aren't in this plugin, which makes me believe another plugin is overriding the /world command. Do you have EssentialCmds installed?

**Comment by Huckletsplay** [comment]
Ya I actually took it out and it works. But, now I feel I messed up my
server trying to import an older world. Something to do with the .lock
http://pastebin.com/Eqr31cd7

**Comment by trentech** [comment]
Closing as command conflict
