### ISSUE TITLE
What sequence of commands do I need to enter to create a world I can go into?

### ISSUE THREAD

**Issue by dpisarenko** [trentech/ProjectWorlds#16]
I'm in the single player mode, in some world and want to create a ProjectWorld where I can go to.

What commands do I need to issue to do that?

I tried this:

* `/world create w1`
* `/world gamemode w1 1`
* `/world teleport w1`

But then I get the error message `w1 does not exist`.

When I enter `/world list`, I get the following output.

![Screenshot](http://i.imgur.com/jAcO3d6.png)

The logical thing to do is to call `/world load w1`, but it also gives me an error (`Foreign world detected`).

![Screenshot](http://i.imgur.com/Pp2yfO8.png)

Then, I try to import it (`/world import w1`), but it also doesn't work (error `w1 is not a valid world`).

![Screenshot](http://i.imgur.com/BK4TD8a.png)

What commands do I need to enter in order to be able to go into the world created using `/world create` ?

**Comment by trentech** [comment]
ProjectWorlds has not had a lot of testing done in single player. Try restarting your client, the newly created world should load automatically.

**Comment by dpisarenko** [comment]
Thanks. It helped.
