### ISSUE TITLE
/world Doesnt work

### ISSUE THREAD

**Issue by BaKuSiN** [trentech/ProjectWorlds#17]
Hi!,
im trying to install this plugin but doesnt work for me. I write "/world", or "/pjw" and say the command doesnt exists, however I write "/sponge plugins" and is listed. I have this things:

- spongeforge-1.8.9-1890-4.1.0-BETA-1379.jar (tried with versions 1378,1374 too)
- projectworlds-4.1.0-0.9.0.jar
- forge 1890

Thanks in advance!

**Comment by trentech** [comment]
Do you have any other plugins installed? try /pjw:world.

I will also note that recent changes to Sponge have broken some things related to teleporting. This shouldn't prevent commands from working, but you will definately notice issues with /world tp, world gamemodes and such.  I believe 1369 is the last build before things break. I'm working on fixing this soon. There are problems with the the last few builds that are preventing me from doing so, so I have no ETA atm.

**Comment by BaKuSiN** [comment]
Thanks for answer!
I changed to 1368 and after put one by one, the plugin works perfectly. The thing is IDK why happened this.
So I will play with this version for max compatibility!

Ty very much <3

**Comment by trentech** [comment]
Just pushed update. Will need build 1380 as build 1370 through 1379 contain a teleport bug.
