### ISSUE TITLE
Is it possible to specify the size of the generated world?

### ISSUE THREAD

**Issue by dpisarenko** [trentech/ProjectWorlds#18]
Imagine, I want to create a world with only one dimension (no end, no nether) and with a pre-defined small size.

Is it possible to specify the size of the new world when running `/world create`, e. g. by specifying `-m`  in [world generation modifiers](https://github.com/trentech/ProjectWorlds/blob/master/src/main/java/com/gmail/trentech/pjw/commands/CMDCreate.java) ? If yes - which modifiers are responsible for the size of the world?

**Comment by trentech** [comment]
A custom modifier would have to be created to accomplish this and even then I'm not sure if it's possible. I don't really understand world modifiers which is why I haven't created any. Honestly i think creating a world border would be your best bet. As far as nether and end I believe they can be disabled in server.properties

**Comment by dpisarenko** [comment]
The problem I'm trying to solve is memory issues. If I create 3 worlds using `/world create`, exit the world and try to open it again, I can't because I get out-of-memory errors.

> Honestly i think creating a world border would be your best bet.

How?

**Comment by trentech** [comment]
Can't you allocate more RAM to your client/server? I don't think making the world smaller is going to make a difference in this case. Unless the chunks are loaded it really doesn't matter how big the world is. Only loaded chunks would be in memory.

http://minecraft.gamepedia.com/World_border

**Comment by dpisarenko** [comment]
Thanks for your answer.

> Can't you allocate more RAM to your client/server?

That's not the answer :)

The answer was to limit the memory of JVM using [-Xmx](http://stackoverflow.com/questions/5374455/what-does-java-option-xmx-stand-for) flag (Minecraft profile, JVM options).
