### ISSUE TITLE
Can't view world properties in /world list when /world is overwritten by another plugin

### ISSUE THREAD

**Issue by Tzky** [trentech/ProjectWorlds#2]
What went wrong
---

When using another plugin which overwrites the ``/world`` command, you can't click on a world in ``/world list`` command to reveal the worlds properties.

What i expected to happen
---

Reveal the properties!

How to reproduce
---

1. Use a plugin which overwrites ``/world`` with its own command. 
2. Do ``/w list`` to open the world list PJW provides
3. PJW will issue ``/world properties #worldname#`` which will fail since ``/world`` got overwritten by said other plugin

**Comment by trentech** [comment]
Fixed in 7f7acf33274a0fbdf5fb3e4f260a9d38886f41bb
