### ISSUE TITLE
world creation modifiers don't seem to work.

### ISSUE THREAD

**Issue by nobotious** [trentech/ProjectWorlds#21]
no matter how i create a world, i cannot get modifiers to work.

i receive no error, but a command such as: 

/world create test -m pjw:void

only creates a plain world
same goes for -m sponge:skylands

mc 1.8.9
spongeapi 4.2.0-snapshot-768e91f
spongeforge 1.8.9-1890-4.2.0-beta-1402
forge 11.15.1.1902

projectworlds- 4.1.0-0.9.1

**Comment by nobotious** [comment]
just looked and saw that you were building with spongeapi 4.1.0, even going back to this does not fix the issue.

**Comment by trentech** [comment]
ccbd8a0ef950a11dbea47f3cf1dfe1ed1276c70c
