### ISSUE TITLE
World fill leaving chunks loaded

### ISSUE THREAD

**Issue by mrdeadlocked** [trentech/ProjectWorlds#23]
It looks like running world fill on the world causes every chunk it generates to stay loaded until server reboot. Should this been saving the world reguarly and unloading those chunks? After running the fill command for a few minutes the progress slows.

I am on forge 12.18.0.2008, the Spongeforge 5.0.0-BETA-1548 and ProjectWorlds-v0.10.1.

world: 3593 Loaded chunks, 1513 Entities
DIM-1: 0 Loaded chunks, 0 Entities
DIM1: 0 Loaded chunks, 0 Entities
DIM-1: Unloaded
DIM1: Unloaded

Dim 0 \: Mean tick time\: 2303.148 ms. Mean TPS\: 0.434
Dim -1 \: Mean tick time\: 0.961 ms. Mean TPS\: 20.000
Dim 1 \: Mean tick time\: 0.783 ms. Mean TPS\: 20.000
Overall \: Mean tick time\: 2404.205 ms. Mean TPS\: 0.416

**Comment by trentech** [comment]
I believe this is a bug in Sponges chunk generator

**Comment by mrdeadlocked** [comment]
I dont seem to have the same issue when I use this:

https://forums.spongepowered.org/t/chunk-pregeneration-utility/12002/3

The loaded chunks never get that high and the TPS never crashes so low.
