### ISSUE TITLE
Worlds imported by ProjectWorlds have a few issues

### ISSUE THREAD

**Issue by OblivionNW** [trentech/ProjectWorlds#24]
I have a world I imported called 'Spawn' (Tested issue with World created by ProjectWorlds, same issue), it is FLAT and of type OVERWORLD but when people login they see it as a nether world but if they go to the real overworld and then go back to the world 'Spawn' they see it as normal. The WorldBorder is also seen in the incorrect location (It also limits movement) and requires you to go to the real overworld and back for it to be fixed.

**Comment by trentech** [comment]
Need more information. Plugin version Sponge version, logs if any, all that

**Comment by OblivionNW** [comment]
0.9.2 (Latest) Project World's
1.8.9 - 4.2.0-BETA-1584 SpongeForge
No errors in logs.

**Comment by OblivionNW** [comment]
Still occurs with PW 0.9.4 and SO build 1666

**Comment by trentech** [comment]
Are you using **/world tp** or some other plugin for teleporting? I'm unable to confirm this issue

**Comment by OblivionNW** [comment]
I have nucleus installed but that's it. To have the issue you need to logout in the PW world and then log back in.

**Comment by trentech** [comment]
4.x build no longer supported
