### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by seanamor** [trentech/ProjectWorlds#25]
Not sure if this is an issue but when I log in I see this error, I have started a new world since I first started using your plugin, if that helps you at all.

projectportals-4.2.0-0.11.2
projectworlds-4.1.0-0.9.1

`23.07 12:34:41 [Server] Server thread/INFO SpongeForge
23.07 12:34:41 [Server] INFO Minecraft: 1.8.9
23.07 12:34:41 [Server] INFO SpongeAPI: 4.2.0-SNAPSHOT-1f5dac2
23.07 12:34:41 [Server] INFO SpongeForge: 1.8.9-1890-4.2.0-BETA-1585
23.07 12:34:41 [Server] INFO Minecraft Forge: 11.15.1.1902`

`23.07 12:29:26 [Server] Netty Epoll Server IO #3/INFO [FML]: Attempting connection with missing mods [sponge, calendar, com.gmail.trentech.customspawners, djxycore, EnjinMinecraftPlugin, com.boydti.fawe, foxcore, foxguard, NameAPI, nucleus, permissionmanager, prism, com.gmail.trentech.pjp, com.gmail.trentech.pjw, net.minecrell.statusprotocol, totaleconomy] at CLIENT
23.07 12:29:26 [Server] Netty Epoll Server IO #3/INFO [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.client.C00PacketKeepAlive
23.07 12:29:27 [Server] Server thread/INFO [FML]: [Server thread] Server side modded connection established
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: org.spongepowered.api.data.persistence.InvalidDataException: Could not deserialize com.gmail.trentech.pjp.data.mutable.HomeData! Don't worry though, we'll try to deserialize the rest of the data.
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:130)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.entity.Entity.readFromNbt(Entity.java:1013)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.entity.EntityLivingBase.readFromNbt(EntityLivingBase.java:180)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.entity.Entity.handler$onReadFromNBT$0(Entity.java:982)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1508)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:279)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.server.management.ServerConfigurationManager.func_72380_a(ServerConfigurationManager.java:281)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:190)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList:131]: 	at java.lang.Thread.run(Thread.java:745)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.util.NoSuchElementException: No value present
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.util.Optional.get(Optional.java:135)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at com.gmail.trentech.pjp.data.builder.manipulator.HomeDataManipulatorBuilder.build(HomeDataManipulatorBuilder.java:31)
23.07 12:29:27 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:124)
23.07 12:29:33 [Multicraft] Skipped 3 lines due to rate limit (29/s)`

**Comment by trentech** [comment]
This is a Project Portals error. If you disabled homes that will cause this error. It's not a huge deal, Just stating it cannot deserialize the HomeData in the PlayerData file. It should go away on it's own.
