### ISSUE TITLE
Crash on new world load

### ISSUE THREAD

**Issue by floh22** [trentech/ProjectWorlds#26]
I can create new worlds and import them as well, but as soon as I load them the server crashes.

Spongeforge: 1.10.2 5.0.0 1659
Project worlds: 5.0.0-0.10.3

http://pastebin.com/XnGdemuD
http://pastebin.com/JUj3TyYA

Please excuse me if i'm being an idiot, but as far as I can tell this happens every time even in a clean environment

**Comment by trentech** [comment]
Looks like a Sponge error to me. I see no reference to Project Worlds

**Comment by floh22** [comment]
hm ok thanks.  I thought maybe project worlds was failing to register the world somewhere, but I guess it really is just a Sponge thing.
