### ISSUE TITLE
Logging in forever

### ISSUE THREAD

**Issue by Daniel12321** [trentech/ProjectWorlds#28]
I use this plugin for my pixelmon server so i can have the spawn in a different world. But whenever the server restarted, when people log in, the server says they logged in fine, but they get stuck on the logging in screen forever. I need to kick them from the server for them to be able to join again, and then the world looks like it is a nether world, while it is not. In the client console, it spams an error: 
![error-projectworlds](https://cloud.githubusercontent.com/assets/20142295/17837200/95c8f87a-67ac-11e6-91a0-f109dcbc3178.png)
Any way i can fix this?

**Comment by trentech** [comment]
I need more to go on than this. Are you sure it's this plugin causing this problem?

**Comment by Daniel12321** [comment]
yes, before we had this plugin, everything worked fine, but now when people log out in the spawn world, it sometimes causes this problem. 
Sponge version: 1.8.9-1890-4.2.0-BETA-1574
ProjectWorlds version: 0.9.4

**Comment by trentech** [comment]
You're over 100 SpongeForge builds outdated.

**Comment by Daniel12321** [comment]
I just updates to the newest version, and it still has the same issue.

**Comment by trentech** [comment]
Idk without any errors related to this plugin I can't make any determinations. I can guess that it's probably pixelmon related. I'll setup a pixelmon test server and see if I can replicate the problem when I have time

**Comment by trentech** [comment]
Does this happen with a world created by this plugin? Are there any modifiers added to the world?
