### ISSUE TITLE
Allow custom alias to prevent other plugins overwrite PJW commands

### ISSUE THREAD

**Issue by Tzky** [trentech/ProjectWorlds#3]
What went wrong
---

when using other plugins (which overwrite ``/world`` command) together with PJW, you can't use PJW properly anymore. 

What i expected to happen
---
Tried using:
* ``/pjw:world``
* ``/project worlds:world``
* ``/w``

How to reproduce
---
1. Use PJW together with another plugin which overwrites ``/world`` command, for ex. EssCmds by Hassan. 
2. try to ``/world``

**Comment by Tzky** [comment]
Related: #2

**Comment by trentech** [comment]
https://github.com/trentech/ProjectWorlds/commit/67beb3fc0e77919fe67baf2f18b0c99ae4fb5d6e configurable aliases

**Comment by trentech** [comment]
Should also mention /pjw:world works now's as well.
