### ISSUE TITLE
Motd on join

### ISSUE THREAD

**Issue by 5tingr4y** [trentech/ProjectWorlds#30]
So, when a player has the `pjw.options.motd` permission, the server motd will be displayed to the player on join. 2 things about this:

1. Why is that even in this plugin anyway? That would be a feature for an essentials plugin like nucleus, nexus or essentials imho. It looks really out of place for a world management plugin. Cause of that, I'd suggest removing it.

2. If you want to keep it, I would suggest adding a config entry to disable this globally. I for example use Pex and have a an operator group with all permissions and I don't want to remove that specific permission (or any permission for that matter) from that group just so I don't get that motd anymore.

**Comment by trentech** [comment]
I agree.

7111253d732dbab00ed6d9c888f2adff2bc4eedf
