### ISSUE TITLE
Newly created worlds don't load.

### ISSUE THREAD

**Issue by Nachty** [trentech/ProjectWorlds#31]
Same problem with v0.9.3 v0.9.4 and v0.10.3.

Whenever I make a new world it says world created. Then when I try to load the world it says that the world doesn't exist. But it does exist in /list and I can rename the world. When I log off and open the world again then it stays infinitely on the loading screen.

I have Minecraft version 1.8.9 installed with forge 11.15.1.1.1890. 
In the following link I will upload a screenshot of all the mods that I have installed on it. 
http://imgur.com/a/HE2bi

Let me know if you need any more information.

I hope you can help fix my problem.

(btw for on sponge forum, tell the guy asking about enabling pixelmon spawns to add the dimension to the list of pixelmon spawns in pixelmon config spawning>spawn dimensions)

**Comment by Nachty** [comment]
I tried it with only spongeforge and ProjectWorlds and I got the same result. (Same spongeforge and forge version)

**Comment by trentech** [comment]
I believe this is connected to this https://github.com/trentech/ProjectWorlds/issues/28

I'm also convinced it's isolated to SpongeForge. I'm checking it out.

**Comment by Nachty** [comment]
Yeah it seemed connected but I wasn't sure if I should comment there or make a new issue since things where a bit different. 
And thanks for looking at it :D
