### ISSUE TITLE
[1.10.2] Foce Gamemode

### ISSUE THREAD

**Issue by mister-man** [trentech/ProjectWorlds#33]
Hallo together,

if I set a gamemode like "/world gamemode <world> [value]", I get an output, that the gamemode was set. But if a player joins the world he is in his last gamemode, not in the gamemode of the world.

Plugins installed:
- PEX
- PJW
- PJP
- RedProtect

Thanks

**Comment by trentech** [comment]
Player needs permission pjw.options.gamemode

**Comment by mister-man** [comment]
Okay, I will try it. Thanks :)

**Comment by mister-man** [comment]
Okay, it works. Sorry it isn't a bug, its a feature :)
