### ISSUE TITLE
[1.10.2] Teleport doesn't work an the tp permission

### ISSUE THREAD

**Issue by mister-man** [trentech/ProjectWorlds#35]
Hello together,

I tried to teleport a player from world1 to world2 and it seems, that is impossible to teleport through dimensions. Further I gave a moderator the permission "pjw.cmd.world.teleport" and "pjw.cmd.world.teleport.others", but they can't use the Command.

Thanks.

**Comment by trentech** [comment]
The ability to teleport other players has been removed in favor of the numerous essential plugins available

**Comment by mister-man** [comment]
Okay, but if I try to teleport myself, with the "pjw.cmd.world.teleport" permission, the server returns no permission for these command.

**Comment by trentech** [comment]
Your going to want to take this up with whatever permission plugin you're using.

**Comment by mister-man** [comment]
Okay, it's pex. Thanks for helping and for further informations. I try it or make a post at pex

thanks
