### ISSUE TITLE
Can't make a Flat world

### ISSUE THREAD

**Issue by Badcholo** [trentech/ProjectWorlds#36]
I can't seem to make a flat world. 
/world create exampleworld OVERWORLD FLAT
/world    even this command doesn't work. it just says not enough arguments
/world create minecraft:the_end   not enough arguments. 
It may be a command thing, so maybe a shortcut like /pw create exampleworld flat

**Comment by trentech** [comment]
This is a command conflict that can be resolved by reading the Sponge docs. This has been discussed numerous times here and the forums.
