### ISSUE TITLE
Unable to save world after calling /world list

### ISSUE THREAD

**Issue by 5tingr4y** [trentech/ProjectWorlds#37]
First up, screenshot:
![2016-09-20_16 51 08](https://cloud.githubusercontent.com/assets/1765895/18713866/1f11f0e4-8014-11e6-9510-55262e78a76b.png)

So basically, when I start the server, I can do /save-all just fine, but when I call /world list to list all worlds, I can't do it anymore. It gives me an error in the chat and throws a bunch of exceptions in the console.

Specs:
Forge: forge-1.10.2-12.18.1.2079-universal.jar
Sponge: forge-1.10.2-12.18.1.2079-universal.jar
Plugins: PermissionsEx-Sponge.jar, Nucleus-0.10.1-S5-1.10.2-plugin.jar, projectworlds-5.0.0-0.10.4.jar (error also occurs with only projectworlds tho)

I am using the default config and have removed the world folder completely before startup.

After I call /world list, any attempt at saving the world fails. I am also kinda confused by the fact that the world list lists DIM1 and DIM-1 twice each, once loaded and once unloaded.

Server log:
http://pastebin.com/M9Tx8yMn

**Comment by trentech** [comment]
https://github.com/trentech/ProjectWorlds/issues/34
