### ISSUE TITLE
[Suggestion] Remove title on first join

### ISSUE THREAD

**Issue by 5tingr4y** [trentech/ProjectWorlds#38]
Similarly to the motd-on-join in #30, I would suggest removing the title that's displayed on first join (that you can change in the config) because imo it'd belong into an essentials plugin like Nexus, Nucleus, etc. and is quite out of place for a world management plugin.

**Comment by trentech** [comment]
Agreed

0b1f88b3cc4a69c50fc660a2921359a9f15c6ee0
