### ISSUE TITLE
Creating new worlds doesn't work anymore.

### ISSUE THREAD

**Issue by Corcustos** [trentech/ProjectWorlds#39]
So I'm trying to create a flatworld called "TwilightZone", and I'm getting problems. I'm using the command "/world create TwilightZone -d overworld -g flat". It keeps saying "something went wrong". It was working prior to a restart, in which I didn't change anything before hand. I also get no error in the console.

Plugin version: projectworlds-4.2.0-0.9.4.jar
Spongeforge version: spongeforge-1.8.9-1890-4.2.0-BETA-1744.jar
Forge version: forge-1.8.9-11.15.1.1902-1.8.9-universal.jar

I'm also using Nucleus-0.10.1-S4-1.8.9-plugin.jar

**Comment by trentech** [comment]
"/world create TwilightZone -d minecraft:overworld -g flat"
