### ISSUE TITLE
Worlds gets unloaded automatically

### ISSUE THREAD

**Issue by Tzky** [trentech/ProjectWorlds#4]
What went wrong
---

When ``/world load`` a custom world, PJW announces an ID conflict and tells the user that it will try to solve the error automatically. Shortly after (~15sec) the world gets unloaded again and the player can't ``/tp`` there. If the player manages to tp himself into the world during this short amount of time, the worlds stays loaded

What i expected to happen
---
* World stays loaded 
* PJW properly solves the ID issue

How to reproduce
---

1. create a server with the 3 vanilla worlds (DIM-1, DIM0, DIM1)
2. try to load another world
3. watch the world burn ;)

**Comment by trentech** [comment]
Still haven't come up with a solution for this, but I'm working on it

**Comment by trentech** [comment]
I'm almost positive this has to do with the default behavior of minecraft. Vanilla and Forge will both unload worlds that are unoccupied. I remember having this problem with Cauldron and Multiverse a couple years back. It seems setting keepSpawnLoaded to true on load or creation prevents this behavior from happening. Next build should help prevent this problem but it's basically just a work around. If admin changes the keepSpawnLoaded flag the problem will return.

**Comment by trentech** [comment]
52d89367d08ff2cd8ea475d53c6e80aa5bc58ef8
