### ISSUE TITLE
Import world bug (maybe)

### ISSUE THREAD

**Issue by guardianzozo** [trentech/ProjectWorlds#42]
Version: projectworlds-5.1.0-0.11.2
Sponge Version : spongeforge-1.10.2-2107-6.0.0-BETA-1844
Forge Version: FTBserver-1.10.2-12.18.2.2107-universal
World Name: world_skylands

Hey there, this may just be a dumb error on my part (first time attempting to use sponge) but i use the command /world import world_skylands XXX (The XXX is where i put in the type) and i keep getting a error of "no values matching pattern 'XXX' present for dimensionType!"

for Dimension Types ive tried Overworld, OVERWORLD, overworld, OverWorld, THE_END, NETHER, Nether and nether

im just trying to add in a old map we used to play awhile ago that has been pregenned (so i dont care if it bugs out at the edges) is this a bug or am i doing something wrong?

**Comment by trentech** [comment]
That's my bad on the lack of documentation. DimensionType is now identified by id to ensure mod compatibility. So instead of Overworld use minecraft:overworld. I do believe tab completion should work so if you type /world import world_skylands then hit tab it should give you a list of available DimensionType's

**Comment by guardianzozo** [comment]
Awesome thank you! but now im getting "not enough arguments" is there anything else im missing? pressing tab is listing the types just with out the mod before it

**Comment by trentech** [comment]
Have you inputted a GeneratorType? Try this

/world import world_skylands minecraft:overworld overworld

**Comment by guardianzozo** [comment]
Awesome! that works granted the map is having issues but i think that might be due to the age of the map now (its a very old map) but now i understand how that works. All thats needed now is to find something to "layer" maps on top of each other again once i somehow update the map lol. But you rock and thanks for the quick replys
