### ISSUE TITLE
Issues importing worlds

### ISSUE THREAD

**Issue by RichterOneZero** [trentech/ProjectWorlds#43]
Good Morning,

I'm having issues importing worlds (non-sponge and SP).

I'm running the command `/world import worldname OVERWORLD`
Which throws the error `No values matching pattern 'OVERWORLD' present for dimensionType!`

![2016-11-08_08 57 25](https://cloud.githubusercontent.com/assets/22287486/20078807/f0e6fdc8-a5a6-11e6-9f02-dee3c8f4b114.png)

I've attempted this with OVERWORLD and THE_END without success, which as far as I can tell are valid dimensionType values.

Running MC 1.10.2, SpongeForge 2107-6.0.0 BETA and Project Worlds 0.11.2

Any help would be appreciated.

-RichterOneZero

**Comment by trentech** [comment]
Tab completion should give you a list of valid DimensionType's. 

You need to specify the modid of the DimensionType. This ensures compatibility with mods.

/world import minecraft:overworld overworld

**Comment by RichterOneZero** [comment]
Awesome, that worked well =).

A further question; when entering /world and selecting an option, I get no help/documentation white text for the command as shown in the screenshots on your page. Just the error "Not enough arguments".
This this a known issue?

Thanks,
RichterOneZero

**Comment by trentech** [comment]
No it's a side effect of some changes made. All the help stuff was moved to 

https://github.com/trentech/HelpMe/releases

I just haven't officially released it yet. Perms are same style, command is /helpme

**Comment by RichterOneZero** [comment]
Thanks! Final question I hope:

I'm trying to execute the copy command. I run the command `/world copy world newworld` but I get the following error:
"Error occurred while executing command: No value present"

I've attempted using the command while the source world is loaded and unloaded, and tried copying over an existing loaded/unloaded world to no effect.

The documentation suggests I only need to supply the source and destination world names, and if I add something after the destination world name, I get the too many arguments error, so I don't believe I'm missing an input?

Thanks,
RichterOneZero

**Comment by trentech** [comment]
Can you send me the error from the console?

**Comment by RichterOneZero** [comment]
I've uploaded it to this [Pastebin page](http://pastebin.com/RvAswp2S)

**Comment by trentech** [comment]
ah you found a bug. ill push an update to fix this

**Comment by trentech** [comment]
545fcd0969179c491486afecdd2de9ff05e86636 fixes issue

**Comment by RichterOneZero** [comment]
Thanks trentech, all working well now. Hopefully its smooth sailing from here =).
