### ISSUE TITLE
Options dont work

### ISSUE THREAD

**Issue by Actavium** [trentech/ProjectWorlds#44]
Hey, it would be nice if you could tell me the propblem :)
Sponge Version: 1.10.2 - 5.1.0-BETA-1879
PJW: projectworlds-5.1.0-0.11.3.jar
Obviously Im using it on MC Version 1.10.2. 
I use it in combination with some other mods on my server but whenever I try another command than "/world create Name" it wont work. 
:c

![2016-11-18_18 26 10](https://cloud.githubusercontent.com/assets/23559409/20439587/83804ece-adbc-11e6-9a16-0337a7e450d6.png)

**Comment by trentech** [comment]
I cannot reproduce this issue. Also your screenshot doesn't match what you are describing. It looks like your running /world enable in the picture.

**Comment by 5tingr4y** [comment]
I think what he means is that he can't click on the entries in the list. I'm having the same problem (clicked on "/world regen"):
![2016-12-11_23 18 36](https://cloud.githubusercontent.com/assets/1765895/21083817/ccfc4154-bff8-11e6-8cd2-940e2a7e3ba6.png)

The console just outputs this:
[23:18:22] [Server thread/INFO] [nucleus]: 5tingr4y ran the command: /world 
[23:18:25] [Server thread/INFO] [nucleus]: 5tingr4y ran the command: /pjw:world regen

Also, manually entering that command doesn't work either.

On a side note I noticed that the /world create entry actually seems to call /world delete.

**Comment by trentech** [comment]
As stated in the Sponge forum thread that feature was moved to https://github.com/trentech/HelpMe/releases

Without this plugin clicking the commands is suppose to show that commands Usage output, however Sponge is bugged so it's only showing the main /world command Usage. This has been bugged for quite sometime and seems to have been neglected by the Sponge team

**Comment by 5tingr4y** [comment]
Hmm yea that worked.

Thanks for the help ^^
