### ISSUE TITLE
Error renaming world

### ISSUE THREAD

**Issue by Stormymystic** [trentech/ProjectWorlds#45]
I do this command:
 /world rename (world) (new name)
I get this error:
Error executing command world is still loaded.
I do this command:
/world unload (world)
I get this message:
(world) unloaded successfully
I repeat previous steps to the same error.
Here is a capture of the plugins I have. I have edited the global.cfg file to try and force /world to only work with PJW, and even doing the /pjw:w rename (world (new name) results in the same error.
![plugins](https://cloud.githubusercontent.com/assets/24259207/20733101/6f3b4a6a-b657-11e6-86c1-1b8871ae1422.PNG)

**Comment by trentech** [comment]
Confirmed. This looks like a Sponge bug. Will be perfoming more tests and submitting ticket on SpongeCommon

**Comment by trentech** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1055

**Comment by trentech** [comment]
ee116d6
