### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by oogienl** [trentech/ProjectWorlds#49]
i have some problems with permissions when my players use /world tp or even /world, they have been added to a specific group and even with all of the permissions set to true from https://forums.spongepowered.org/t/project-worlds-v0-11-4-world-manager/10170 they still get the message ''no permission''. my admins have no problems using these commands so my question is, is there another permission i have to fill in here? because things like pjw.cmd.world.teleport do not work.

running spongeforge-1.10.2-2202-5.1.0-BETA-2029
Minecraft 1.10.2
projectworlds-5.1.0-0.11.4

**Comment by trentech** [comment]
You probably need to assign the permission node for the actual world itself. pjw.worlds.[world]
