### ISSUE TITLE
World generator modifiers are not recognized properly

### ISSUE THREAD

**Issue by Minecrell** [trentech/ProjectWorlds#5]
There seem to be a few problems with the way you support the world generator modifiers.  If I register my world generator modifier early enough it seems to get registered by your plugin just fine, however with a few minor problems:

- You use `WorldGeneratorModifier.getName()` which is not guaranteed to be unique. You should use `getId()` here instead, especially because the names can also contain spaces or other special characters.

- You convert all arguments into upper case, so if I have a lower case name your plugin is currently unable to find the world generator modifier. (If you use `Sponge.getRegistry().getType(WorldGeneratorModifier.class, name)` instead it should be case-insensitive).

Just a few suggestions to make them work properly. Thanks :)

**Comment by trentech** [comment]
I see you pointed out something I missed when I re wrote the world creation command. I think that might explain a few problems I've been having. Changes will be updated in next build

**Comment by trentech** [comment]
My tests confirm these changes resolve most world creation problems, the only gripe I have is modifier id's are normally formatted pluginid:modifier which is more of a cosmetic annoyance than anything, but other than that, Thanks for pointing out these issues

**Comment by trentech** [comment]
resolved in 52d89367d08ff2cd8ea475d53c6e80aa5bc58ef8
