### ISSUE TITLE
World Properties not working

### ISSUE THREAD

**Issue by TheSpicePhantom** [trentech/ProjectWorlds#51]
Every time I want to create a void world, it gives me a normal type map and I can't seem to find an option to change this.

**Comment by trentech** [comment]
You can't change a world once it has been created. Can you verify the void modifier is being applied by running /world properties <world>

**Comment by TheSpicePhantom** [comment]
Thanks I'm sorry for not correcting the issue as solved I found out how it
works in a recent post. Thanks anyways

Am 11.02.2017 2:47 nachm. schrieb "trentech" <notifications@github.com>:

You can't change a world once it has been created. Can you verify the void
modifier is being applied by running /world properties

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/trentech/ProjectWorlds/issues/51#issuecomment-279144772>,
or mute the thread
