### ISSUE TITLE
Gamemode doesnt update on world change

### ISSUE THREAD

**Issue by turtledude01** [trentech/ProjectWorlds#52]
Changing from world1 which is survival, to world2 which is creative does not update gamemode at all.  I have tried setting the gamerule forceGamemode to true globally and on each world, and also have the gamemode set correctly on each world.

**Comment by trentech** [comment]
There's a permission node that overrides this behavior. pjw.override.gamemode. Make sure your not testing with an OP or admin

**Comment by turtledude01** [comment]
Ah, yep that is working now, didn't see that permission thanks
