### ISSUE TITLE
Creating Worlds

### ISSUE THREAD

**Issue by TheSpicePhantom** [trentech/ProjectWorlds#54]
Hi, I got a new Problem,
I wanted to create a world with this command:
/world create SkyClaims -d minecraft:overworld -g overworld -m sponge:skylands

And all I get is an Error where the Plugin seems to be asking for a "GAMEMODE", I wonder why a world would want a gamemode for creation, well yeah I dont seem to get it working. 
Please Help.

**Comment by trentech** [comment]
Sounds like Nucleus, not ProjectWorlds. Most likely a command conflict
