### ISSUE TITLE
Can't Import Existing Worlds

### ISSUE THREAD

**Issue by SjsolisZXA** [trentech/ProjectWorlds#56]
Whenever I try to import a world with "/world import NAME_OF_WORLD", I get a "Not enough arguments!" exception. This has happened to me in the past, but I got around it by creating a new world with "/world create NAME_OF_WORLD", shutting down the server, deleting the recently created world and pasting in the world I originally wanted to import.

**Comment by trentech** [comment]
`/world import <name> <dimensionType> <generatorType>`
