### ISSUE TITLE
Numeric seeds are not handled properly

### ISSUE THREAD

**Issue by Minecrell** [trentech/ProjectWorlds#6]
Currently the world seeds always [get hashed, even if you type in a numeric one](https://github.com/trentech/ProjectWorlds/blob/master/src/com/gmail/trentech/pjw/commands/CMDCreate.java#L165). For seeds this should only use `.hashCode()` if the given input is not already a long that can be parsed. This prevents using numeric seeds properly currently.

**Comment by trentech** [comment]
Good catch. Updated in next build

**Comment by trentech** [comment]
Resolved in 52d89367d08ff2cd8ea475d53c6e80aa5bc58ef8
