### ISSUE TITLE
Cant start Server

### ISSUE THREAD

**Issue by Sclane1** [trentech/ProjectWorlds#63]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2379.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 21.06.17 07:16
Description: Exception in server tick loop

Missing Mods:
	helpme : 0.2.3

net.minecraftforge.fml.common.MissingModsException: Mod pjw (Project Worlds) requires [helpme@0.2.3]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:536)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:536)

-- Sponge CauseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zhn000(MinecraftServer.java:3937)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:361)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:503)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1487401520 bytes (1418 MB) / 1926758400 bytes (1837 MB) up to 1926758400 bytes (1837 MB)
	JVM Flags: 2 total; -Xms2G -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281-universal.jar) 
	U	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281-universal.jar) 
	U	spongeapi{5.2.0-SNAPSHOT-ab52c0c} [SpongeAPI] (minecraft.jar) 
	U	sponge{1.10.2-2281-5.2.0-BETA-2379} [SpongeForge] (spongeforge-1.10.2-2281-5.2.0-BETA-2379.jar) 
	U	clearmob{1.3.1} [ClearMob] (ClearMob-1.3.1.jar) 
	U	mmcreboot{2.0.4} [MMCReboot] (MMCReboot-2.0.4-API-5.1-6.X.jar) 
	U	permissionmanager{3.0.1} [PermissionManager] (permissionmanager-3.0.1.jar) 
	U	pjc{0.1.0} [Project Core] (project core-5.2.0-0.1.0.jar) 
	U	pjp{0.13.7} [Project Portals] (project portals-5.2.0-0.13.7.jar) 
	U	pjw{0.11.5} [Project Worlds] (project worlds-5.1.0-0.11.5.jar) 
	U	pji{0.10.0} [Project Inventories] (project.inventories-5.2.0-0.10.0.jar) 
	U	ultimatechat{1.7.1} [UltimateChat] (UltimateChat-1.7.1-b22.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.10.2-2281-5.2.0-BETA-2379.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

Where i can get this Sponge-Plugin helpme?

**Comment by Sclane1** [comment]
When i make a new Test-Server with Sponge 6.0.0 for 1.10.2 (Minecraft)
i can load the PJC and PJW 6.1.0 but i cant create a Portal to the World that i create.
Every time i get a Error

**Comment by trentech** [comment]
`U	pjw{0.11.5} [Project Worlds] (project worlds-5.1.0-0.11.5.jar)`

Update PJW to latest 5.2.0 version

The other issue I'd need more details, but sounds like a PJP issue
