### ISSUE TITLE
helpme 0.2.3 is a dependancy?

### ISSUE THREAD

**Issue by gigafunk** [trentech/ProjectWorlds#64]
With latest dev build for 5.2 I get this with projectworlds, when i have project core and walletdrop already on and working at latest versions.    I cant find much info on helpme beside a git repository for it. Is it required or an oversight from 6.0 development?  Two dependencies doesnt seem right. 
Or maybe its intended. 

net.minecraftforge.fml.common.MissingModsException: Mod pjw (Project Worlds) requires [helpme@0.2.3]

either way, thanks for your cool plugins! I just want to make sure this helpme is required before I add more stuff. i have a heavily modded server and less is more. I appreciate the portals being spun off into a different module.

**Comment by trentech** [comment]
HelpMe was discontinued in the latest releases. The components were merged into the ProjectCore library. You can delete HelpMe from your server.

**Comment by trentech** [comment]
Oh crap I think I forgot to merge something. I see the mistake but I'm not home so I can't fix it right now

**Comment by gigafunk** [comment]
No problem! Its just good to know I am not crazy. Yeah it wouldnt boot
without it. I am in no hurry! No sweat...it is a dev build after all!
Thanks triple for your cool work.
