### ISSUE TITLE
Don't create world if world generator modifiers cannot be found

### ISSUE THREAD

**Issue by Minecrell** [trentech/ProjectWorlds#7]
It is pretty annoying if you want to create a world, and don't type the world generator modifier correctly, the plugin will create the world anyway, just without the generator modifier. I think this should instead cancel the world creation, because that way you always need to unload, and delete the world first.

**Comment by trentech** [comment]
Yeah you're right. I can't remember why I designed it the way it is but I can see that getting annoying. Will be fixed in next push

**Comment by trentech** [comment]
https://github.com/trentech/ProjectWorlds/commit/8d059ff2668c25b9b1ce49795f4f2099a0b9a29a
