### ISSUE TITLE
Command conflict

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [trentech/ProjectWorlds#70]
the /world commands is being overriden by another plugin (https://nucleuspowered.org)

I need nucleus for many many other reasons, but would like the "world" part handled by this...
Any way to fix ???

**Comment by trentech** [comment]
This has been covered several times in the Sponge forums

https://forums.spongepowered.org/t/conflicting-plugin-commands-look-no-further-use-command-aliases/11011
