### ISSUE TITLE
I cannot use this Mod

### ISSUE THREAD

**Issue by FroggerTkL** [trentech/ProjectWorlds#71]
EVERYTIME! Everytime I try to start up a server, I need some stupid requirement for a mod...

My server crashes on startup and keeps telling me the following: 

net.minecraftforge.fml.common.MissingModsException: Mod pjw (ProjectWorlds for SpongeAPI 5.x) requires [pjc]Missing Mods:pjc : any

I need an answer for this ASAP! I cannot find this stupid mod and Google does not help -_-

**Comment by wunder-bread** [comment]
If you took the time to read the whole page before you installed it.
http://trentech.org/jenkins/job/ProjectCore%20for%20SpongeAPI%205.x/
