### ISSUE TITLE
pjw error on world list command on 1.11.2 

### ISSUE THREAD

**Issue by kain184** [trentech/ProjectWorlds#74]
sponge version spongeforge-1.11.2-2393-6.1.0-BETA-2606.jar mod version projectworlds-7.0.0-0.12.0.jar 
any idea what this is or why it is happening
10.09 09:49:11 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'world list' for source EntityPlayerMP['kain184'/142, l='gameworld', x=2090.42, y=226.56, z=1737.51]: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)Lorg/spongepowered/api/service/pagination/PaginationList; 10.09 09:49:11 [Server] INFO java.lang.NoSuchMethodError: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)Lorg/spongepowered/api/service/pagination/PaginationList; 10.09 09:49:11 [Server] INFO at com.gmail.trentech.pjw.commands.CMDList.execute(CMDList.java:60) ~[CMDList.class:?] 10.09 09:49:11 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:182) ~[ChildCommandElementExecutor.class:1.11.2-2393-6.1.0-BETA-2606] 10.09 09:49:11 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.11.2-2393-6.1.0-BETA-2606] 10.09 09:49:11 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.11.2-2393-6.1.0-BETA-2606] 10.09 09:49:11 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:296) ~[SpongeCommandManager.class:1.11.2-2393-6.1.0-BETA-2606] 10.09 09:49:11 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?] 10.09 09:49:11 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) ~[mi.class:?] 10.09 09:49:11 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) ~[mi.class:?] 10.09 09:49:11 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[ip.class:?] 10.09 09:49:11 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[ip.class:?] 10.09 09:49:11 [Server] INFO at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:145) ~[PacketUtil.class:1.11.2-2393-6.1.0-BETA-2606] 10.09 09:49:11 [Server] INFO at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.11.2-2393-6.1.0-BETA-2606] 10.09 09:49:11 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:144) [PacketUtil.class:1.11.2-2393-6.1.0-BETA-2606] 10.09 09:49:11 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjm000(SourceFile:539) [fo$1.class:?] 10.09 09:49:11 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?] 10.09 09:49:11 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131] 10.09 09:49:11 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131] 10.09 09:49:11 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] 10.09 09:49:11 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:257) [SpongeImplHooks.class:1.11.2-2393-6.1.0-BETA-2606] 10.09 09:49:11 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zhl000(MinecraftServer.java:3972) [MinecraftServer.class:?] 10.09 09:49:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?] 10.09 09:49:11 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?] 10.09 09:49:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?] 10.09 09:49:11 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?] 10.09 09:49:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by alphawolf918** [comment]
Getting the same issue.

**Comment by trentech** [comment]
spongeforge-1.11.2-2393-**_6.1.0_**-BETA-2606.jar
projectworlds-**_7.0.0_**-0.12.0.jar

Version mismatch.
