### ISSUE TITLE
Can not set gamerules

### ISSUE THREAD

**Issue by Danickar** [trentech/ProjectWorlds#75]
No matter what I type in, I get the response "rule" is not a valid Value for Gamerule.

For example:
/world gamerule MyWorld doMobSpawning false
Returns:
doMobSpawning is not a valid Value for Gamerule doMobSpawning

**Comment by Danickar** [comment]
Looking at your code, I think the problem is on like 89 of the CommandGameRule.java file.

You have : `value = args[1];`
I believe that should be: `value = args[2]; `

**Comment by trentech** [comment]
resolved 8b75598a7625f38762b28fae00dfb82d61c181aa
