### ISSUE TITLE
Loading any world

### ISSUE THREAD

**Issue by MysteryQuestMan** [trentech/ProjectWorlds#78]
I've installed worlds and core and running sponge 5.2.0 on Minecraft-hosting.pro
My issue comes when I try to load a world. they world shows up on the list and I can do almost anything with it, but the second I try to load it always says the same thing

![2018-01-14_03 56 57](https://user-images.githubusercontent.com/26530745/34914377-a8f3ab5a-f8df-11e7-8875-9da7d681bbdc.png)

'Preparing to load the world. This may take a few minutes"
"Could not load  'worldname'"

this happens with any world, spawned or imported. how do i fix this?

**Comment by trentech** [comment]
5.2.0 is no longer supported. Reopen ticket if problem occurs with latest version
