### ISSUE TITLE
Can't use BiomesOPlenty mod's generator

### ISSUE THREAD

**Issue by zch12138** [trentech/ProjectWorlds#79]
Hello, I am using the BETA-2842 sponge forge. I can't use BIOMESOP generator when I use this plugin to create a new world. I am sure the BiomesOPlenty is work and it is the latest version. When I type "/world create test -g BIOMESOP" it said "BIOMESOP is not a valid GeneratorType". Was it a projectworlds's bug?

**Comment by trentech** [comment]
Try this biomesoplenty:b_i_o_m_e_s_o_p
