### ISSUE TITLE
[Discrepancy] ProjectWorlds stops working when using UltimateChat

### ISSUE THREAD

**Issue by wolfity50** [trentech/ProjectWorlds#84]
After setting up the ProjectWorlds plugin to move between the worlds, I installed UltimateChat and after rebooting the server, I found that ProjectWorlds did not work. There are no error messages in the console. Is there any solution to this problem?

This is strange. I was even surprised. I checked it again, but nothing has changed. The commands are also inaccessible. Here logs:
[withoutUltimateChat.txt](https://github.com/trentech/ProjectWorlds/files/1787726/withoutUltimateChat.txt)
[withUltimateChat.txt](https://github.com/trentech/ProjectWorlds/files/1787727/withUltimateChat.txt)

**Comment by trentech** [comment]
From my testing, Project Worlds is loading, but UltimateChat is completely overriding my command registration..This may need to be reported with the UltimateChat developer

**Comment by trentech** [comment]
OK seems that removing 'w' from the cmd-aliases node in the config.conf for ultimatechat resolves the issue.
